title: The I.T. Guy
baseline: Tech and Culture
baseurl: /
canonicalurl: true
description: ...the trials and trivial triumphs of a freelance dev in the City.
pagination:
  max: 5
  path: page
date:
  format: j F Y
  timezone: Europe/Paris
theme: hyde
netlify:
  cms:
    path: admin
    version: latest
  identity:
    version: v1
